[33m0a9e68e[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mmin[m[33m, [m[1;31morigin/min[m[33m)[m 1
[33m7e6818d[m 메인화면 수정본_1
[33m702c727[m 메인화면
[33mc9bf777[m 화면 연결 중
[33m2ccba71[m[33m ([m[1;31morigin/master[m[33m, [m[1;31morigin/HEAD[m[33m)[m Merge pull request #1 from seungc1/chan
[33mad30a18[m Clean Architecture 초기 구조 설정 (Domain, Data Layer 및 Hilt DI)
[33m6915954[m 모델 필드값 설정
[33m7751c3c[m[33m ([m[1;31morigin/won[m[33m)[m 씨발 드디어 환경설정 완료?
[33mcfc41e5[m 1
[33m1fbbc64[m 1
[33m112546b[m 1
[33m261678e[m test
[33m51bda58[m test
[33m68b9ae0[m Apply proper gitignore and refresh index
[33m1cf36e6[m first test
